# Generated by Django 5.2.16 on 2026-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_type',
            field=models.CharField(choices=[('profit', 'سود'), ('risk', 'ریسک'), ('order', 'نظم'), ('learning', 'یادگیری')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
