# Generated by Django 5.2.16 on 2026-08-19 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_risk', models.IntegerField(default=0)),
                ('max_loss_daily', models.IntegerField(default=0)),
                ('max_loss_weekly', models.IntegerField(default=0)),
                ('max_transaction_daily', models.IntegerField(default=0)),
                ('max_consecutive_loss', models.IntegerField(default=0)),
                ('min_r_r', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riskmanages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
