# Generated by Django 5.2.16 on 2026-09-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0005_alter_portfolio_is_active'),
        ('app_riskmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskmanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='portfolio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
