# Generated by Django 5.2.16 on 2026-10-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_riskmanage', '0002_remove_riskmanagement_user_riskmanagement_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='max_consecutive_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='max_loss_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='max_loss_weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='max_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='max_transaction_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='min_r_r',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
