# Generated by Django 5.2.16 on 2026-08-10 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Transaction ID must be in the format T-123.', regex='^T-\\d+$')])),
                ('symbol', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('risk_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('followed_plan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
