# Generated by Django 5.2.16 on 2026-08-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0004_merge_20260827_0658'),
        ('app_transaction', '0003_transaction_r_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
