# Generated by Django 5.2.16 on 2026-09-02 14:43

import app_transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0005_transaction_mt_ticket_alter_transaction_r_r_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatraderaccount',
            name='investor_password_encrypted',
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='api_key',
            field=models.CharField(default=app_transaction.models.generate_api_key, max_length=64, unique=True),
        ),
    ]
