# Generated by Django 5.2.16 on 2026-09-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0005_alter_portfolio_is_active'),
        ('app_transaction', '0006_remove_metatraderaccount_investor_password_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatraderaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='portfolio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mt_account', to='app_portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
