# Generated by Django 5.2.16 on 2026-09-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0005_alter_portfolio_is_active'),
        ('app_transaction', '0007_remove_metatraderaccount_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatraderaccount',
            name='is_connected',
        ),
        migrations.RemoveField(
            model_name='metatraderaccount',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='metatraderaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metatraderaccount',
            name='api_key',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metatraderaccount',
            name='platform',
            field=models.CharField(default='mt5', max_length=10),
        ),
        migrations.AlterField(
            model_name='metatraderaccount',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_accounts', to='app_portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='metatraderaccount',
            name='server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mt_ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
