# Generated by Django 5.2.16 on 2026-09-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0005_alter_portfolio_is_active'),
        ('app_transaction', '0008_remove_metatraderaccount_is_connected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatraderaccount',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mt_account', to='app_portfolio.portfolio'),
        ),
    ]
