# Generated by Django 5.2.16 on 2026-10-01 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_portfolio', '0005_alter_portfolio_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('api', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_report', models.TextField()),
                ('trading_regime', models.IntegerField(default=0)),
                ('capital_management', models.IntegerField(default=0)),
                ('psychology', models.IntegerField(default=0)),
                ('adherence_to_the_plan', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='app_portfolio.portfolio')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ai_analysis.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReportDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('transaction_count', models.IntegerField(default=0)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adherence_to_the_plan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('best_trade', models.TextField()),
                ('worst_trade', models.TextField()),
                ('golden_window', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ai_analysis.aianalysis')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReportWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('description', models.TextField()),
                ('transaction_count', models.IntegerField(default=0)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adherence_to_the_plan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('best_trade', models.TextField()),
                ('worst_trade', models.TextField()),
                ('golden_window', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ai_analysis.aianalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Strengths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('maintaining_sustainability', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ai_analysis.aianalysis')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ai_analysis.aianalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Weaknesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('solution', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ai_analysis.aianalysis')),
            ],
        ),
    ]
