# Generated by Django 5.2.16 on 2026-10-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
