# Generated by Django 5.2.16 on 2026-10-01 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai_analysis', '0002_aimodel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
