# Generated by Django 5.2.16 on 2026-10-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai_analysis', '0003_aianalysis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
