# Generated by Django 5.2.16 on 2026-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai_analysis', '0004_aimodel_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='api',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='api_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
