# Generated by Django 5.2.16 on 2026-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai_analysis', '0005_remove_aimodel_api_aimodel_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
