# Generated by Django 5.2.16 on 2026-10-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai_analysis', '0007_aianalysisrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='used_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text='Cumulative number of tokens consumed by this model.'),
        ),
    ]
