# Generated by Django 5.2.16 on 2026-09-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0003_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='risk_up_warning_notif',
            field=models.BooleanField(default=True),
        ),
    ]
