# Generated by Django 5.2.16 on 2026-10-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_badge', '0003_badge_acquisition_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='trigger_type',
            field=models.CharField(choices=[('plan_streak', 'روزهای متوالی پایبند به پلن'), ('drawdown_reduction', 'کاهش دراودان'), ('no_revenge_trade', 'روزهای بدون Revenge Trade'), ('trade_count', 'تعداد معاملات'), ('profit_factor', 'Profit Factor'), ('no_emotional_entry', 'روزهای بدون ورود احساسی'), ('first_trade', 'اولین معامله'), ('journal_streak', 'روزهای متوالی ژورنال\u200cنویسی'), ('profitable_month', 'ماه سودده'), ('win_rate', 'Win Rate'), ('risk_management', 'مدیریت ریسک'), ('no_overtrading', 'بدون Overtrading'), ('capital_double', 'دابل کردن سرمایه'), ('a_plus_streak', 'معاملات A+ متوالی'), ('mt_connection', 'اتصال متاتریدر'), ('checklist_master', 'استاد چک\u200cلیست')], max_length=50),
        ),
    ]
