from decimal import Decimal
from django.test import TestCase
from django.urls import reverse
from rest_framework.test import APIClient

from app_portfolio.models import Portfolio
from app_transaction.models import Transaction, MetaTraderAccount
from app_user.models import User


class TransactionTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(
            email='t@example.com', password='pass12345', phone='09127000000'
        )
        self.user.is_verified = True
        self.user.save(update_fields=['is_verified'])
        self.portfolio = Portfolio.objects.create(
            user=self.user, name='P', broker='XM', balance=Decimal('1000.00'),
            is_active=True,
        )
        self.client.force_authenticate(user=self.user)

    def _tx(self, **kw):
        data = dict(
            portfolio=self.portfolio, symbol='EURUSD', transaction_type='buy',
            entry_price=Decimal('1.10000000'), volume=Decimal('0.10000000'),
        )
        data.update(kw)
        return Transaction.objects.create(**data)

    def test_transaction_id_autogenerated_sequential(self):
        t1 = self._tx()
        t2 = self._tx()
        self.assertEqual(t1.transaction_id, 'T-1')
        self.assertEqual(t2.transaction_id, 'T-2')

    def test_profit_loss_computed_on_save(self):
        t = self._tx(volume=Decimal('1.00000000'), exit_price=Decimal('1.11000000'))
        self.assertIsNotNone(t.profit_loss)
        self.assertGreater(t.profit_loss, 0)

    def test_total_reward_property(self):
        t = self._tx(exit_price=Decimal('1.11000000'))
        self.assertIsNotNone(t.total_reward)

    def test_create_transaction_via_post(self):
        resp = self.client.post('/app/trades/', {
            'symbol': 'EURUSD',
            'transaction_type': 'buy',
            'entry_price': '1.10000000',
            'volume': '0.10000000',
        }, format='json')
        self.assertEqual(resp.status_code, 201, resp.data)
        self.assertTrue(Transaction.objects.filter(portfolio=self.portfolio).exists())

    def test_create_transaction_without_active_portfolio(self):
        self.portfolio.is_active = False
        self.portfolio.save(update_fields=['is_active'])
        resp = self.client.post('/app/trades/', {
            'symbol': 'EURUSD', 'transaction_type': 'buy',
            'entry_price': '1.10000000', 'volume': '0.10000000',
        }, format='json')
        self.assertEqual(resp.status_code, 404)

    def test_transaction_list_requires_active_portfolio(self):
        self.portfolio.is_active = False
        self.portfolio.save(update_fields=['is_active'])
        resp = self.client.get('/app/trades/')
        self.assertEqual(resp.status_code, 404)

    def test_transaction_list_paginated(self):
        for _ in range(15):
            self._tx()
        resp = self.client.get('/app/trades/')
        self.assertEqual(resp.status_code, 200, resp.data)
        self.assertEqual(len(resp.data['transactions']), 10)

    def test_calendar_invalid_month(self):
        resp = self.client.get('/app/trades/trades/calendar/1403/13/')
        self.assertEqual(resp.status_code, 400)

    def test_calendar_ok(self):
        resp = self.client.get('/app/trades/trades/calendar/1403/1/')
        self.assertEqual(resp.status_code, 200, resp.data)
        self.assertIn('calendar', resp.data)

    def test_import_report_wrong_file_type(self):
        from django.core.files.uploadedfile import SimpleUploadedFile
        f = SimpleUploadedFile('x.txt', b'hello', content_type='text/plain')
        resp = self.client.post('/app/trades/add/import/', {
            'portfolio_id': self.portfolio.pk, 'file': f,
        }, format='multipart')
        self.assertEqual(resp.status_code, 400)

    def test_mt_account_connected_property(self):
        acc = MetaTraderAccount.objects.create(portfolio=self.portfolio)
        self.assertFalse(acc.connected)
        self.assertTrue(acc.api_key)
