# Generated by Django 5.2.16 on 2026-10-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('API', models.CharField(max_length=100)),
                ('requests_token', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
