# Generated by Django 5.2.16 on 2026-08-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_user_created_at_user_status_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('', 'Free'), ('pro', 'Pro'), ('pro max', 'ProMax')], default='', max_length=7),
        ),
    ]
