# Generated by Django 5.2.16 on 2026-10-07 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_alter_user_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
