# Generated by Django 5.2.16 on 2026-08-24 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('leverage', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('mt_connection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
