# Generated by Django 6.1 on 2026-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('USDT', 'USDT'), ('IRR', 'IRR')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='leverage',
            field=models.CharField(choices=[('1:1', '1:1'), ('1:30', '1:30'), ('1:100', '1:100'), ('1:200', '1:200'), ('1:500', '1:500')], default='1:1', max_length=10),
        ),
    ]
