# Generated by Django 6.1 on 2026-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_alter_portfolio_currency_alter_portfolio_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
