# Generated by Django 6.1 on 2026-08-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_portfolio_is_archived_alter_portfolio_currency_and_more'),
        ('app_portfolio', '0003_portfolio_is_archived'),
    ]

    operations = [
    ]
