# Generated by Django 5.2.16 on 2026-09-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0004_merge_20260827_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
