# Generated by Django 5.2.16 on 2026-08-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feel', models.CharField(choices=[('comfort', 'آرام'), ('concentrated', 'متمرکز'), ('greed', 'طمع'), ('fear', 'ترس'), ('revenge', 'انتقام')], default='comfort', max_length=20)),
                ('mistakes', models.TextField()),
                ('lesson_learned', models.TextField()),
                ('followed_plan', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
