# Generated by Django 5.2.16 on 2026-09-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0002_journal_transaction_journal_user'),
        ('app_portfolio', '0005_alter_portfolio_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AddField(
            model_name='journal',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='app_portfolio.portfolio'),
        ),
    ]
